server:
  port: 6548
spring:
  flyway:
    user: Jokail
    password: 12345678
    baseline-on-migrate: true
  datasource:
    password: 12345678
    username: Jokail
    url: jdbc:mysql://localhost:3306/main
  jpa:
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    root: info

#---
#spring:
#  profiles:
#    active: prod
#logging:
#  level:
#    root: off