server:
  port: 6548
spring:
  flyway:
    user: temic
    password: 505606
    baseline-on-migrate: true
  datasource:
    password: 505606
    username: temic
    url: jdbc:mysql://localhost:3306/main
  jpa:
    hibernate:
      ddl-auto: validate
logging:
  level:
    root: info

#---
#spring:
#  profiles:
#    active: prod
#logging:
#  level:
#    root: off